from __future__ import annotations

import argparse
import json
import os
from datetime import date, datetime, timedelta
from pathlib import Path

import pandas as pd


EXCLUDE_STATUSES = {"OUT", "DOUBTFUL", "SUSPENDED", "INACTIVE", "REST"}


def _parse_date(s: str) -> date:
    return datetime.strptime(s, "%Y-%m-%d").date()


def _daterange(start: date, end: date):
    d = start
    while d <= end:
        yield d
        d += timedelta(days=1)


def _norm_bool_str(x) -> str:
    try:
        s = str(x).strip().lower()
    except Exception:
        return ""
    if s in {"true", "1", "yes", "y"}:
        return "true"
    if s in {"false", "0", "no", "n"}:
        return "false"
    return s


def _is_season_exclusion(status_series: pd.Series) -> pd.Series:
    st = status_series.astype(str).str.upper().str.strip()
    return (
        (st.str.contains("SEASON", na=False) & st.str.contains("OUT", na=False))
        | st.str.contains("INDEFINITE", na=False)
        | st.str.contains("SEASON-ENDING", na=False)
    )


def main() -> None:
    ap = argparse.ArgumentParser(description="Audit stale injury exclusions across a date range.")
    ap.add_argument("--start", type=str, default=None, help="YYYY-MM-DD (default: end-13d)")
    ap.add_argument("--end", type=str, default=date.today().isoformat(), help="YYYY-MM-DD")
    ap.add_argument("--max-conflicts", type=int, default=200, help="Limit conflicts output")
    args = ap.parse_args()

    end = _parse_date(args.end)
    start = _parse_date(args.start) if args.start else (end - timedelta(days=13))

    repo_root = Path(__file__).resolve().parent.parent
    _DATA_ROOT = os.environ.get("NBA_BETTING_DATA_ROOT")
    data_root = Path(_DATA_ROOT).expanduser() if _DATA_ROOT else (repo_root / "data")
    processed = data_root / "processed"

    conflicts: list[dict] = []
    days_scanned = 0

    for d in _daterange(start, end):
        ds = d.isoformat()
        pp_path = processed / f"props_predictions_{ds}.csv"
        if not pp_path.exists():
            continue
        days_scanned += 1

        # players expected to be playing today based on props_predictions
        try:
            pp = pd.read_csv(pp_path)
        except Exception:
            continue
        if pp is None or pp.empty or ("team" not in pp.columns) or ("player_name" not in pp.columns):
            continue

        pp = pp.copy()
        pp["team"] = pp["team"].astype(str).str.upper().str.strip()
        pp["player_name"] = pp["player_name"].astype(str).str.strip()
        pp = pp[pp["player_name"].ne("")].copy()

        if "playing_today" in pp.columns:
            pt = pp["playing_today"].map(_norm_bool_str)
            pp_play = pp[pt.eq("true")].copy()
        else:
            pp_play = pp.iloc[0:0].copy()

        # excluded map as generated by CLI (post-fix): use the same logic by importing cli helper
        # but without depending on click invocation.
        try:
            from nba_betting.cli import _smart_sim_run_date  # type: ignore
        except Exception:
            _smart_sim_run_date = None

        # If we can't import, just skip range audit.
        if _smart_sim_run_date is None:
            raise SystemExit("Could not import nba_betting.cli; run inside repo venv.")

        # Reconstruct excluded map by calling the private builder via a tiny shim:
        # we can't access the nested function directly, so we approximate by reading
        # injuries_excluded_<date>.csv + raw injuries.csv and then removing anyone in pp_play.
        excl = set()
        try:
            ie = processed / f"injuries_excluded_{ds}.csv"
            if ie.exists():
                df = pd.read_csv(ie)
                if df is not None and not df.empty:
                    tcol = "team_tri" if "team_tri" in df.columns else ("team" if "team" in df.columns else None)
                    ncol = "player" if "player" in df.columns else ("player_name" if "player_name" in df.columns else None)
                    if tcol and ncol:
                        df = df.copy()
                        if "status" in df.columns:
                            st = df["status"].astype(str).str.upper().str.strip()
                            season_out = _is_season_exclusion(df["status"])
                            df = df[st.isin(EXCLUDE_STATUSES) | season_out].copy()
                        if "date" in df.columns:
                            cutoff = pd.to_datetime(ds, errors="coerce")
                            if pd.notna(cutoff):
                                df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.date
                                df = df[df["date"].notna() & (df["date"] <= cutoff.date())].copy()
                                fresh_cutoff = (cutoff - timedelta(days=30)).date()
                                season_out = _is_season_exclusion(df.get("status", pd.Series(dtype=str)))
                                df = df[(df["date"] >= fresh_cutoff) | season_out].copy()
                                df = df.sort_values(["date"]).groupby([ncol, tcol], as_index=False).tail(1)
                        for _, r in df[[tcol, ncol]].dropna().iterrows():
                            tri = str(r.get(tcol) or "").strip().upper()
                            nm = str(r.get(ncol) or "").strip()
                            if tri and nm:
                                excl.add((tri, nm))
        except Exception:
            pass

        # Remove allowlisted (playing) players
        allow = set()
        try:
            for _, r in pp_play[["team", "player_name"]].dropna().iterrows():
                allow.add((str(r.get("team") or "").strip().upper(), str(r.get("player_name") or "").strip()))
        except Exception:
            allow = set()

        for tri, nm in sorted(excl):
            if (tri, nm) in allow:
                conflicts.append({"date": ds, "team": tri, "player": nm, "reason": "in_injuries_excluded_but_playing_today"})
                if len(conflicts) >= int(args.max_conflicts):
                    break
        if len(conflicts) >= int(args.max_conflicts):
            break

    print(
        json.dumps(
            {
                "start": start.isoformat(),
                "end": end.isoformat(),
                "days_scanned": days_scanned,
                "conflicts": conflicts,
                "conflicts_n": len(conflicts),
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
